import React, {Suspense} from 'react';
import './App.css';
// import {withTranslation} from "react-i18next";
import {withTranslation} from 'react-i18next';
import Lobby from "./Lobby"
import Game from "./Game"
import PropTypes from 'prop-types';

import ReactFlagsSelect from 'react-flags-select';
//import css module
import 'react-flags-select/css/react-flags-select.css';
//OR import sass module
import 'react-flags-select/scss/react-flags-select.scss';

//https://react.i18next.com/guides/quick-start#translate-your-content


class AppCo extends React.Component {

    constructor(props) {
        super(props);
        //asl
        console.log('AppCo constructor');
        this.state = this.getInitialState();
        console.log(props);
        console.log(this.state);
        this.gameSelected = this.gameSelected.bind(this);
    }

    getInitialState = () => {
        let path = document.location.pathname.slice(1);
        if (path) {
            return {gameID: path}
        }
        if (document.location.hash) {
            return {gameID: document.location.hash.slice(1)};
        }
        if (window.selectedGameID) {
            return {gameID: window.selectedGameID}
        }
        return {gameID: null};
    };

    gameSelected = (game) => {
        this.setState({gameID: game.id});
        document.location.pathname = '/' + game.id;
    };

    changeLang = (e) => {
        this.props.i18n.changeLanguage(e)
    };

    render() {
        const {t} = this.props;

        let pane;
        if (this.state.gameID) {
            console.log('<GAME>');

            pane = (<Game gameID={this.state.gameID}/>)
        } else {
            console.log('<LOBBY>');
            pane = (<Lobby gameSelected={this.gameSelected} defaultGameID={window.autogeneratedGameID}/>)
        }

        return (
            <div id="application">
                <div id="topbar">
                    <a href={window.location.origin}>
                        <h1>{t('title')}</h1>
                    </a>
                    <ReactFlagsSelect
                        defaultCountry="PL"
                        countries={["GB", "PL"]}
                        customLabels={{"GB": "English", "PL": "Polski"}}
                        onSelect={this.changeLang}/>
                </div>
                {pane}
            </div>

        );
    }
}

const AppComponent = withTranslation()(AppCo);

AppComponent.propTypes = {
    gameID: PropTypes.string,
    gameSelected: PropTypes.string,
};

// i18n translations might still be loaded by the xhr backend
// use react's Suspense
export default function App() {
    return (
        <Suspense fallback="loading">
            {/*<AppCo/>*/}
            <AppComponent/>
        </Suspense>
    );
}